### ISSUE TITLE
Проблема на билдсервере

### ISSUE THREAD

**Issue by skyline-gleb** [2gis/Winium.Cruciatus#32]
И это возможно проблема метода в том числе. Суть - тест на GetFocusedElement падает если в этот момент на билдмашине открыта папка с выделенным элементом и тогда два варианта, либо приложение открывается за папкой и тычок действительно не в приложение происходит, либо возвращается не верный элемент (либо не успевает быть сфокусированным либо есть разные типы фокусов....)

**Comment by bangonkali** [comment]
Hi, This is a really impressive software. But can you write some of the issues in English. I am interested in supporting this effort. Thanks!

**Comment by sanjeets** [comment]
Impressive but still an hackathon type of an effort.
I am trying stuff and its not working

**Comment by NickAb** [comment]
@sanjeets could you describe what is not working? We use it in quite a few commands to run automated functional UI tests on CI.

**Comment by NickAb** [comment]
@bangonkali we will try to write all important issues in english. This issues is related to the rare problem of driver clicking into wrong window if you have any other apps opened on the desktop where the tests are running and your app did not go into top most foreground position due to long start or something like that.
